/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
class AppTest {
    String inputFilePath = "C:\\Users\\Lenovo\\OneDrive\\Desktop\\java\\bitmap-transformer\\bitmap\\app\\src\\main\\resources\\me2.bmp";
    String outputFilePath = "C:\\Users\\Lenovo\\OneDrive\\Desktop\\java\\bitmap-transformer\\bitmap\\app\\src\\main\\resources\\";
    String grayFile = "motasim.bmp";
    Bitmap testFile = new Bitmap(inputFilePath, outputFilePath, grayFile);
    @Test
    public void testReadFile() {
        assertEquals(testFile.readFile(),true,"File not found");
    }
    @Test
    public void testSaveFile() {
        testFile.readFile();
        assertEquals(testFile.saveFile(),true,"File not saved");
    }
    @Test
    public void testGray() {
        testFile.readFile();
        assertEquals(testFile.grayScale(),true);
    }
    @Test
    public void testImageFlipHorizontal() {
        testFile.readFile();
        int lastRGBVal = -10124662;
        assertEquals(testFile.imageFlipHorizontal(),lastRGBVal,"File not flipped horizontally");
    }
    @Test
    public void testImageFlipVertical() {
        testFile.readFile();
        int lastRGBVal = -5720134;
        assertEquals(testFile.imageFlipVertical(),lastRGBVal,"File not flipped vertically");
    }
}